# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegelstand', '0002_auto_20170501_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegelzeit',
            name='zeittext',
            field=models.CharField(default='notim', max_length=5),
        ),
    ]
