# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegelstand', '0003_pegelzeit_zeittext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pegel_long',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pegel_html_titel', models.CharField(default='999: Leerer Datensatz', max_length=30)),
                ('pegel_html_long', models.CharField(default='999: Leerer Datensatz', max_length=16000)),
                ('pegel_html_zeitstempel', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
