# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegelstand', '0004_pegel_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegel_long',
            name='pegel_html_long',
            field=models.TextField(default='999: Leerer Datensatz'),
        ),
    ]
